### ISSUE TITLE
Optimise with Options

### ISSUE THREAD

**Issue by stevenwhitespacesystems** [smartmonkeyio/smartmonkey-services-js#1]
In your documentation here
[https://docs.smartmonkey.io/#/flake/optimizer-v1](https://docs.smartmonkey.io/#/flake/optimizer-v1)

You have additional parameters rewards and options, however I can't seem to see how you add these to the optimize() function.

Is this possible or could you amend the function to include these as additional parameters on the optimize() function.

**Comment by pablomartinezm** [comment]
You're right, we'll be adding this parameters ASAP

**Comment by pablomartinezm** [comment]
Solved in #2 
version 1.0.6 will be uploaded soon to npm

**Comment by stevenwhitespacesystems** [comment]
Thanks for the prompt response!
